version: '2'
services:
  torproxy:
    image: jess/tor-proxy
    expose:
      - "9050"
    restart: "always"
  privoxy:
    image: jess/privoxy
    links:
      - torproxy
    expose:
      - "8118"
  bot1-pokego:
    build: .
    environment:
      - HTTPS_PROXY=privoxy:8118
      - HTTP_PROXY=privoxy:8118
    volumes:
     - ./configs:/usr/src/app/configs
     - ./web:/usr/src/app/web
    stdin_open: true
    tty: true
  bot1-pokegoweb:
    image: python:2.7
    ports:
     - "8000:8000"
    volumes_from:
      - bot1-pokego
    volumes:
      - ./configs:/usr/src/app/web/config
    working_dir: /usr/src/app/web
    command: bash -c "echo 'Serving HTTP on 0.0.0.0 port 8000' && python -m SimpleHTTPServer > /dev/null 2>&1"
    depends_on:
     - bot1-pokego
